# Generated by Django 4.1.5 on 2023-01-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('speech', models.TextField(blank=True, max_length=10000, null=True)),
                ('background', models.FileField(upload_to='static/images')),
                ('scene_prompts', models.TextField(max_length=10000)),
            ],
        ),
    ]
